//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        public Aula()
        {
            this.Docente = new HashSet<Docente>();
            this.recuperaciones = new HashSet<recuperaciones>();
        }
    
        public string IdAula { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Capacidad_Aula { get; set; }
        public string IdPabellon { get; set; }
        public string Id_tipo_aula { get; set; }
    
        public virtual tipo_aula tipo_aula { get; set; }
        public virtual Pabellon Pabellon { get; set; }
        public virtual ICollection<Docente> Docente { get; set; }
        public virtual ICollection<recuperaciones> recuperaciones { get; set; }
    }
}
