//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente
    {
        public int IdCodigo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string DNI { get; set; }
        public string Estado_Servicio { get; set; }
        public string correo { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public int Celular { get; set; }
        public string Direccion { get; set; }
        public int IdTipoDocente { get; set; }
        public string IdGrado { get; set; }
        public string IdFacultad { get; set; }
        public Nullable<bool> sexo { get; set; }
        public string IdAula { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual Facultad Facultad { get; set; }
        public virtual Grado_Docente Grado_Docente { get; set; }
        public virtual Tipo_Docente Tipo_Docente { get; set; }
    }
}
