//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escuela
    {
        public Escuela()
        {
            this.Curso = new HashSet<Curso>();
            this.recuperaciones = new HashSet<recuperaciones>();
        }
    
        public int IdEscuela { get; set; }
        public string Descripcion { get; set; }
        public string IdFacultad { get; set; }
    
        public virtual ICollection<Curso> Curso { get; set; }
        public virtual Facultad Facultad { get; set; }
        public virtual ICollection<recuperaciones> recuperaciones { get; set; }
    }
}
