//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facultad
    {
        public Facultad()
        {
            this.Docente = new HashSet<Docente>();
            this.Escuela = new HashSet<Escuela>();
        }
    
        public string IdFacultad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Docente> Docente { get; set; }
        public virtual ICollection<Escuela> Escuela { get; set; }
    }
}
