//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class hora
    {
        public hora()
        {
            this.recuperaciones = new HashSet<recuperaciones>();
        }
    
        public string idhora { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> Hora_inicio { get; set; }
        public Nullable<System.DateTime> Hora_fin { get; set; }
    
        public virtual ICollection<recuperaciones> recuperaciones { get; set; }
    }
}
