//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pabellon
    {
        public Pabellon()
        {
            this.Aula = new HashSet<Aula>();
        }
    
        public string IdPabellon { get; set; }
        public Nullable<int> Capacidad_total_Pabellon { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string IdDescripPabellon { get; set; }
    
        public virtual ICollection<Aula> Aula { get; set; }
        public virtual Descrip_Pabellon Descrip_Pabellon { get; set; }
    }
}
