//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class recuperaciones
    {
        public string idrecuperaciones { get; set; }
        public string descripcion { get; set; }
        public string fk_IdFecha { get; set; }
        public string fk_d_Aula { get; set; }
        public string IdHora { get; set; }
        public string IdDia { get; set; }
        public string IdCapacidad { get; set; }
        public string IdClasificacion { get; set; }
        public string IdSeccion { get; set; }
        public int IdEscuela { get; set; }
        public int Fk_idcurso { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual capacidad capacidad { get; set; }
        public virtual clasificacion clasificacion { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual dia dia { get; set; }
        public virtual Escuela Escuela { get; set; }
        public virtual fecha fecha { get; set; }
        public virtual hora hora { get; set; }
        public virtual seccion seccion { get; set; }
    }
}
